import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  ezofflinepapiSidebar: [{ type: 'autogenerated', dirName: 'ezofflinepapi' }, { type: 'link', label: '下载', href: '/download/ezofflinepapi' }],
  easybotSidebar: [
    {
      type: 'html',
      value: "<div class='flex gap-2 justify-center items-center p-5 -ml-5 flex-row text-2xl select-none'> <img width='48px' src='/icon/easybot.png' draggable='false' /> <div>EasyBot</div> </div>"
    },
    "easybot/intor",
    {
      type: 'category',
      label: '快速开始',
      collapsible: true,
      collapsed: false,
      items: {
        "1.安装主程序": [
          "easybot/quick_start/install_windows",
          "easybot/quick_start/install_linux",
          "easybot/quick_start/install_docker",
        ],
        "2.安装插件": [
          "easybot/quick_start/plugin/bukkit/install_bukkit",
          "easybot/quick_start/plugin/be/install_be",
          {
            "MCDR": [
              "easybot/quick_start/plugin/mcdr/install_mcdr",
              "easybot/quick_start/plugin/mcdr/config/index",
              "easybot/quick_start/plugin/mcdr/command/index",
            ]
          }
        ],
        "3.安装机器人": [
          "easybot/quick_start/robot/index",
          {
            "NapCat": [
              "easybot/quick_start/robot/napcat_windows/install_napcat_windows",
              "easybot/quick_start/robot/napcat_docker/install_napcat_docker"
            ]
          },
          "easybot/quick_start/robot/lagrange/lagrange"
        ],
        "4.可选配置": [
          "easybot/quick_start/on_public/index"
        ]
      },
    },
    {
      type: 'category',
      label: '功能文档',
      collapsible: true,
      collapsed: false,
      items: [
        "easybot/features/bind/index",
        {
          "命令列表": [
            "easybot/features/command/index",
            "easybot/features/command/text_only/index",
            "easybot/features/command/run_command/index",
            "easybot/features/command/placeholder/index",
          ]
        },
        {
          "消息同步": [
            "easybot/features/sync/index",
            "easybot/features/sync/to_group/index",
            "easybot/features/sync/to_server/index",
            "easybot/features/sync/custom/index",
          ]
        },
        {
          "图片模板": [
            "easybot/features/image_template/intor",
            "easybot/features/image_template/keyword/index",
            {
              "type": "link",
              "label": "模板市场",
              "href": "https://bbs.hualib.com/"
            }
          ]
        },
        {
          "AI功能": [
            "easybot/features/ai/index",
            "easybot/features/ai/siliconflow/index",
            "easybot/features/ai/deepseek/index"
          ]
        },
        "easybot/features/player_state",
        "easybot/features/placeholder_api"
      ],
    },
    {
      type: 'category',
      label: '常见问题',
      collapsible: true,
      collapsed: false,
      items: [
        "easybot/other/cmi/index",
        "easybot/other/command_fail/index",
        {
          "主程序问题": [
            "easybot/other/main_proc/port/index",
            "easybot/other/main_proc/ssl/index",
          ]
        }
      ]
    },
    {
      type: 'category',
      label: '扩展功能',
      collapsible: true,
      collapsed: false,
      items: [
        "easybot/ext/qface/index",
      ]
    },
    {
      type: 'category',
      label: '开发教程',
      collapsible: false,
      collapsed: false,
      items: {
        "图片模板开发教程": [
          "easybot/dev/image_template/index",
          "easybot/dev/image_template/manifest",
          "easybot/dev/image_template/command",
          "easybot/dev/image_template/dp",
          "easybot/dev/image_template/context",
          "easybot/dev/image_template/placeholder",
          "easybot/dev/image_template/servers",
          "easybot/dev/image_template/viewport",
          "easybot/dev/image_template/vite_react/vite_react"
        ],
      },
    },
    {
      type: 'category',
      label: "下载",
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'link',
          label: '主程序下载',
          href: '/download/easybot'
        },
        {
          type: 'link',
          label: '插件下载',
          href: '/download/easybot_plugin'
        }
      ]
    }
  ]

};

export default sidebars;
